server/mhn/__init__.py
from urlparse import urljoin

from flask import Flask, request, jsonify, abort, url_for, session
from flask_sqlalchemy import SQLAlchemy
from flask_security import Security, SQLAlchemyUserDatastore
from flask_security.utils import encrypt_password as encrypt
from flask_mail import Mail
from werkzeug.contrib.atom import AtomFeed
import xmltodict
import uuid
import random
import string
from flask_wtf.csrf import CSRFProtect

csrf = CSRFProtect()

db = SQLAlchemy()
# After defining `db`, import auth models due to
# circular dependency.
from mhn.auth.models import User, Role, ApiKey
user_datastore = SQLAlchemyUserDatastore(db, User, Role)


mhn = Flask(__name__)
mhn.config.from_object('config')
csrf.init_app(mhn)

# Email app setup.
mail = Mail()
mail.init_app(mhn)

# Registering app on db instance.
db.init_app(mhn)

# Setup flask-security for auth.
Security(mhn, user_datastore)

# Registering blueprints.
from mhn.api.views import api
mhn.register_blueprint(api)

from mhn.ui.views import ui
mhn.register_blueprint(ui)

from mhn.auth.views import auth
mhn.register_blueprint(auth)

# Trigger templatetag register.
from mhn.common.templatetags import format_date
mhn.jinja_env.filters['fdate'] = format_date

from mhn.auth.contextprocessors import user_ctx
mhn.context_processor(user_ctx)

from mhn.common.contextprocessors import config_ctx
mhn.context_processor(config_ctx)

import logging
from logging.handlers import RotatingFileHandler

mhn.logger.setLevel(logging.INFO)
formatter = logging.Formatter(
      '%(asctime)s -  %(pathname)s - %(message)s')
handler = RotatingFileHandler(
        mhn.config['LOG_FILE_PATH'], maxBytes=10240, backupCount=5)
handler.setLevel(logging.INFO)
handler.setFormatter(formatter)
mhn.logger.addHandler(handler)
if mhn.config['DEBUG']:
    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    console.setFormatter(formatter)
    mhn.logger.addHandler(console)


@mhn.route('/feed.json')
def json_feed():
    feed_content = get_feed().to_string()
    return jsonify(xmltodict.parse(feed_content))


@mhn.route('/feed.xml')
def xml_feed():
    return get_feed().get_response()


def makeurl(uri):
    baseurl = mhn.config['SERVER_BASE_URL']
    return urljoin(baseurl, uri)


def get_feed():
    from mhn.common.clio import Clio
    from mhn.auth import current_user
    authfeed = mhn.config['FEED_AUTH_REQUIRED']
    if authfeed and not current_user.is_authenticated:
        abort(404)
    feed = AtomFeed('MHN HpFeeds Report', feed_url=request.url,
                    url=request.url_root)
    sessions = Clio().session.get(options={'limit': 1000})
    for s in sessions:
        feedtext = u'Sensor "{identifier}" '
        feedtext += '{source_ip}:{source_port} on sensorip:{destination_port}.'
        feedtext = feedtext.format(**s.to_dict())
        feed.add('Feed', feedtext, content_type='text',
                 published=s.timestamp, updated=s.timestamp,
                 url=makeurl(url_for('api.get_session', session_id=str(s._id))))
    return feed


def create_clean_db():
    """
    Use from a python shell to create a fresh database.
    """
    with mhn.test_request_context():
        db.create_all()
        # Creating superuser entry.
        superuser = user_datastore.create_user(
                email=mhn.config.get('SUPERUSER_EMAIL'),
                password=encrypt(mhn.config.get('SUPERUSER_PASSWORD')))
        adminrole = user_datastore.create_role(name='admin', description='')
        user_datastore.add_role_to_user(superuser, adminrole)
        user_datastore.create_role(name='user', description='')
        db.session.flush()

        apikey = ApiKey(user_id=superuser.id, api_key=str(uuid.uuid4()).replace("-", ""))
        db.session.add(apikey)
        db.session.flush()

        from os import path

        from mhn.api.models import DeployScript, RuleSource
        from mhn.tasks.rules import fetch_sources
        # Creating a initial deploy scripts.
        # Reading initial deploy script should be: ../../scripts/
        #|-- deploy_conpot.sh
        #|-- deploy_dionaea.sh
        #|-- deploy_snort.sh
        #|-- deploy_kippo.sh
        deployscripts = [
            ['Ubuntu - Conpot', '../scripts/deploy_conpot.sh'],
            ['Ubuntu - Drupot', '../scripts/deploy_drupot.sh'],
            ['Ubuntu - Wordpot', '../scripts/deploy_wordpot.sh'],
            ['Ubuntu - Shockpot', '../scripts/deploy_shockpot.sh'],
            ['Ubuntu - p0f', '../scripts/deploy_p0f.sh'],
            ['Ubuntu - Suricata', '../scripts/deploy_suricata.sh'],
            ['Ubuntu - Glastopf', '../scripts/deploy_glastopf.sh'],
            ['Ubuntu - ElasticHoney', '../scripts/deploy_elastichoney.sh'],
            ['Ubuntu - Amun', '../scripts/deploy_amun.sh'],
            ['Ubuntu - Snort', '../scripts/deploy_snort.sh'],
            ['Ubuntu - Cowrie', '../scripts/deploy_cowrie.sh'],
            ['Ubuntu 14.04/Centos 7 - Dionaea', '../scripts/deploy_dionaea.sh'],
            ['Raspberry Pi - Dionaea', '../scripts/deploy_raspberrypi.sh'],
            ['Ubuntu - Dionaea with HTTP', '../scripts/deploy_dionaea_http.sh'],
            ['Ubuntu - Shockpot Sinkhole', '../scripts/deploy_shockpot_sinkhole.sh'],
        ]
        for honeypot, deploypath in reversed(deployscripts):

            with open(path.abspath(deploypath), 'r') as deployfile:
                initdeploy = DeployScript()
                initdeploy.script = deployfile.read()
                initdeploy.notes = 'Initial deploy script for {}'.format(honeypot)
                initdeploy.user = superuser
                initdeploy.name = honeypot
                db.session.add(initdeploy)

        # Creating an initial rule source.
        rules_source = mhn.config.get('SNORT_RULES_SOURCE')
        if not mhn.config.get('TESTING'):
            rulesrc = RuleSource()
            rulesrc.name = rules_source['name']
            rulesrc.uri = rules_source['uri']
            rulesrc.name = 'Default rules source'
            db.session.add(rulesrc)
            db.session.commit()
            fetch_sources()

server/mhn/api/__init__.py
class APIModel(object):
    @classmethod
    def fields(cls):
        return cls.all_fields.keys()

    @classmethod
    def editable_fields(cls):
        return cls._make_field_list('editable')

    @classmethod
    def required_fields(cls):
        return cls._make_field_list('required')

    @classmethod
    def _make_field_list(cls, prop):
        """
        Returns a list of field names that have the property
        `prop` in the `all_fields` dictionary defined at
        class level.
        """
        return [f for f, e in cls.all_fields.items() if e.get(prop, False)]

    @classmethod
    def check_required(cls, payload):
        """
        Returns a list of required fields that are
        missing from the dictionary object `payload`.
        """
        missing = []
        for field in cls.required_fields():
            if (field not in payload) or payload.get(field) == '':
                missing.append(field)
        return missing

server/mhn/tasks/__init__.py
from celery import Celery

from mhn import mhn


celery = Celery(include=['mhn.tasks.rules'])
celery.conf.update(mhn.config)
TaskBase = celery.Task
class ContextTask(TaskBase):
    abstract = True
    def __call__(self, *args, **kwargs):
        with mhn.app_context():
            return TaskBase.__call__(self, *args, **kwargs)
celery.Task = ContextTask

server/mhn/ui/views.py
from datetime import datetime, timedelta
from pygal.style import *
import pygal
from flask import (
        Blueprint, render_template, request, url_for,
        redirect, g)
from flask_security import logout_user as logout
from sqlalchemy import desc, func

from mhn.ui.utils import get_flag_ip, get_sensor_name
from mhn.api.models import (
        Sensor, Rule, DeployScript as Script,
        RuleSource)
from mhn.auth import login_required, current_user
from mhn.auth.models import User, PasswdReset, ApiKey
from mhn import db, mhn
from mhn.common.utils import (
        paginate_options, alchemy_pages, mongo_pages)
from mhn.common.clio import Clio

ui = Blueprint('ui', __name__, url_prefix='/ui')
from mhn import mhn as app

PYGAL_CONFIG = pygal.config.Config()
PYGAL_CONFIG.js = (
    'https://kozea.github.io/pygal.js/javascripts/svg.jquery.js',
    'https://kozea.github.io/pygal.js/javascripts/pygal-tooltips.js',
)

@app.template_filter()
def number_format(value):
    return '{:,d}'.format(value)

@ui.before_request
def check_page():
    """
    Cleans up any query parameter that is used
    to build pagination.
    """
    try:
        page = int(request.args.get('page', 1))
    except ValueError:
        page = 1
    g.page = page


@ui.route('/login/', methods=['GET'])
def login_user():
    if current_user.is_authenticated:
        return redirect(url_for('ui.dashboard'))
    return render_template('security/login_user.html')


@mhn.route('/')
@ui.route('/dashboard/', methods=['GET'])
@login_required
def dashboard():
    clio = Clio()
    # Number of attacks in the last 24 hours.
    attackcount = clio.session.count(hours_ago=24)
    # TOP 5 attacker ips.
    top_attackers = clio.session.top_attackers(top=5, hours_ago=24)
    # TOP 5 attacked ports
    top_ports = clio.session.top_targeted_ports(top=5, hours_ago=24)
    #Top 5 honey pots with counts
    top_hp = clio.session.top_hp(top=5, hours_ago=24)
    #Top Honeypot sensors
    top_sensor = clio.session.top_sensor(top=5, hours_ago=24)
    # TOP 5 sigs
    freq_sigs = clio.hpfeed.top_sigs(top=5, hours_ago=24)
    
    return render_template('ui/dashboard.html',
                           attackcount=attackcount,
                           top_attackers=top_attackers,
                           top_ports=top_ports,
                           top_hp=top_hp,
                           top_sensor=top_sensor,
                           freq_sigs=freq_sigs,
                           get_sensor_name=get_sensor_name,
                           get_flag_ip=get_flag_ip)


@ui.route('/attacks/', methods=['GET'])
@login_required
def get_attacks():
    clio = Clio()
    options = paginate_options(limit=10)
    options['order_by'] = '-timestamp'
    total = clio.session.count(**request.args.to_dict())
    sessions = clio.session.get(
            options=options, **request.args.to_dict())
    sessions = mongo_pages(sessions, total, limit=10)
    return render_template('ui/attacks.html', attacks=sessions,
                           sensors=Sensor.query, view='ui.get_attacks',
                           get_flag_ip=get_flag_ip, get_sensor_name=get_sensor_name,
                           **request.args.to_dict())

@ui.route('/feeds/', methods=['GET'])
@login_required
def get_feeds():
    clio = Clio()
    options = paginate_options(limit=10)
    options['order_by'] = '-_id'
    count,columns,feeds = clio.hpfeed.get_payloads(options, request.args.to_dict())
    channel_list = clio.hpfeed.channel_map.keys()
    feeds = mongo_pages(feeds, count, limit=10)
    return render_template('ui/feeds.html', feeds=feeds, columns=columns,
                           channel_list=channel_list, view='ui.get_feeds',
                           **request.args.to_dict())

@ui.route('/rules/', methods=['GET'])
@login_required
def get_rules():
    if 'sig_name' in request.args:
        search = '%%%s%%' % request.args.get('sig_name')
        rules = db.session.query(Rule, func.count(Rule.rev).label('nrevs')).\
            filter(Rule.message.like(search)).\
            group_by(Rule.sid).\
            order_by(desc(Rule.date))
    else:
        rules = db.session.query(Rule, func.count(Rule.rev).label('nrevs')).\
            group_by(Rule.sid).\
            order_by(desc(Rule.date))
    rules = alchemy_pages(rules, limit=10)
    return render_template('ui/rules.html', rules=rules, view='ui.get_rules', **request.args.to_dict())


@ui.route('/rule-sources/', methods=['GET'])
@login_required
def rule_sources_mgmt():
    sources = RuleSource.query
    return render_template('ui/rule_sources_mgmt.html', sources=sources)


@ui.route('/sensors/', methods=['GET'])
@login_required
def get_sensors():
    sensors = Sensor.query.all()
    total = Sensor.query.count()
    # Paginating the list.
    pag = paginate_options(limit=10)
    sensors = sensors[pag['skip']:pag['skip'] + pag['limit']]
    # Using mongo_pages because it expects paginated iterables.
    sensors = mongo_pages(sensors, total, limit=10)
    return render_template('ui/sensors.html', sensors=sensors,
                           view='ui.get_sensors', pag=pag)


@ui.route('/add-sensor/', methods=['GET'])
@login_required
def add_sensor():
    return render_template('ui/add-sensor.html')


@ui.route('/manage-deploy/', methods=['GET'])
@login_required
def deploy_mgmt():
    script_id = request.args.get('script_id')
    if not script_id or script_id == '0':
        script = Script(name='', notes='', script='')
    else:
        script = Script.query.get(script_id)
    return render_template(
            'ui/script.html', scripts=Script.query.order_by(Script.date.desc()),
            script=script)

@ui.route('/honeymap/', methods=['GET'])
@login_required
def honeymap():
    return render_template('ui/honeymap.html')

@ui.route('/add-user/', methods=['GET'])
@login_required
def settings():
    return render_template(
        'ui/settings.html', 
        users=User.query.filter_by(active=True),
        apikey=ApiKey.query.filter_by(user_id=current_user.id).first()
    )


@ui.route('/forgot-password/<hashstr>/', methods=['GET'])
def forgot_passwd(hashstr):
    logout()
    user = PasswdReset.query.filter_by(hashstr=hashstr).first().user
    return render_template('ui/reset-password.html', reset_user=user,
                           hashstr=hashstr)


@ui.route('/reset-password/', methods=['GET'])
def reset_passwd():
    return render_template('ui/reset-request.html')


def get_credentials_payloads(clio):
    credentials_payloads = []
    credentials_payloads += clio.hpfeed.get_payloads({'limit':10000},{"channel":"kippo.sessions"})[2]
    credentials_payloads += clio.hpfeed.get_payloads({'limit':10000},{"channel":"cowrie.sessions"})[2]
    return credentials_payloads

@app.route('/image/top_passwords.svg')
@login_required
def graph_passwords():
    clio=Clio()
    
    bar_chart = pygal.Bar(style=LightColorizedStyle,show_x_labels=True, config=PYGAL_CONFIG)
    bar_chart.title = "Cowrie password"
    clio=Clio()
    top_passwords = clio.hpfeed.count_passwords(get_credentials_payloads(clio))
    for password in top_passwords:
        bar_chart.add(password[0],[{'label':str(password[0]),'xlink':'','value':password[1]}])

    return bar_chart.render_response()

@app.route('/image/top_users.svg')
@login_required
def graph_users():
    clio=Clio()
    
    bar_chart = pygal.Bar(style=LightColorizedStyle,show_x_labels=True, config=PYGAL_CONFIG)
    bar_chart.title = "Cowrie username"
    clio=Clio()
    top_users =clio.hpfeed.count_users(get_credentials_payloads(clio))
    for user in top_users:
        bar_chart.add(user[0],[{'label':str(user[0]),'xlink':'','value':user[1]}])

    return bar_chart.render_response()


@app.route('/image/top_combos.svg')
@login_required
def graph_combos():
    clio=Clio()
    
    bar_chart = pygal.Bar(style=LightColorizedStyle,show_x_labels=True, config=PYGAL_CONFIG)
    bar_chart.title = "Cowrie combos"
    clio=Clio()
    top_combos =clio.hpfeed.count_combos(get_credentials_payloads(clio))
    for combo in top_combos:
        bar_chart.add(combo[0],[{'label':str(combo[0]),'xlink':'','value':combo[1]}])

    return bar_chart.render_response()


def top_kippo_cowrie_attackers(clio):
    top_attackers = []
    top_attackers += clio.session._tops('source_ip', 10, honeypot='kippo')
    top_attackers += clio.session._tops('source_ip', 10, honeypot='cowrie')

    import collections
    grouped = collections.Counter()
    for attacker in top_attackers:
        grouped[attacker['source_ip']] += int(attacker['count'])
    return [{'source_ip': ip, 'count': count} for ip, count in sorted(grouped.items(), key=lambda x: x[1], reverse=True)]

@app.route('/image/top_sessions.svg')
@login_required
def graph_top_attackers():
    clio=Clio()
    
    bar_chart = pygal.Bar(style=LightColorizedStyle,show_x_labels=True, config=PYGAL_CONFIG)
    bar_chart.title = "Cowrie attacks"
    clio=Clio()
    top_attackers = top_kippo_cowrie_attackers(clio)
    print top_attackers    
    for attacker in top_attackers:
        bar_chart.add(str(attacker['source_ip']), attacker['count'])

    return bar_chart.render_response()



@ui.route('/chart')
def chart():
    return render_template('ui/chart.html')

server/mhn/templates/base.html
<!doctype html>
<meta charset="UTF-8">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <title>{% block extra_head %}{% endblock %}</title>
        <script src="/static/js/vendor/jquery.js"></script>
        <link rel="stylesheet" href="/static/css/foundation.min.css">
        <link rel="stylesheet" href="/static/css/normalize.css">
        <script src="/static/js/vendor/foundation.min.js"></script>
        <script src="/static/js/vendor/modernizr.js"></script>
        <script src="/static/js/main.js"></script>
    </head>
    <body>
        {% if user.is_authenticated %}
        <nav class="top-bar" style="margin-bottom: 30px;"  data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="{{ url_for('ui.dashboard') }}">蜜罐之心</a></h1>
                </li>
            </ul>
            <section class="top-bar-section">
                <!-- Left Nav Section -->
                <ul class="left">
                    <li><a href="{{ url_for('ui.honeymap') }}">地图</a></li>
                    <li><a href="{{ url_for('ui.deploy_mgmt') }}">部署蜜罐</a></li>
                    <li><a href="{{ url_for('ui.get_attacks') }}">记录的攻击</a></li>
                    <li><a href="{{ url_for('ui.get_feeds', channel='snort.alerts') }}">捕获的事件</a></li>
                    <li class="has-dropdown">
                        <a href="{{ url_for('ui.get_rules') }}">规则</a>
                        <ul class="dropdown">
                            <li><a href="{{ url_for('ui.get_rules') }}">启用规则/关闭规则</a></li>
                            <li><a href="{{ url_for('ui.rule_sources_mgmt') }}">规则来源</a></li>
                            <li><a href="/static/mhn.rules">规则下载</a></li>
                        </ul>
                    </li>
                    <li class="has-dropdown">
                        <a href="{{ url_for('ui.get_sensors') }}">传感器</a>
                        <ul class="dropdown">
                            <li><a href="{{ url_for('ui.get_sensors') }}">查看传感器</a></li>
                            <li><a href="{{ url_for('ui.add_sensor') }}">添加传感器</a></li>
                        </ul>
                    </li>



			 <li class="has-dropdown">
                        <a href="/ui/chart">cowrie表</a>
                        <ul class="dropdown">
                            <li><a href="/image/top_passwords.svg">Cowrie密码捕获情况排名</a></li>
                            <li><a href="/image/top_users.svg">Cowrie用户名捕获情况排名</a></li>
                            <li><a href="/image/top_combos.svg">Cowrie用户名密码组合情况排名</a></li>
                            <li><a href="/image/top_sessions.svg">Cowrie攻击者排名</a></li>
                        </ul>
                    </li>
                </ul>




                <!-- Right Nav Section -->
                <ul class="right">
                    <li class="active"><a id="out-btn" href="#">退出登录</a></li>
                </ul>
                {% if current_user.has_role('admin') %}
                <ul class="right">
                    <li class=""><a id="out-btn" href="{{ url_for('ui.settings') }}">设置</a></li>
                </ul>
                {% endif %}
            </section>
        </nav>
        {% endif %}
        {% block content %}{% endblock %}
        {% block footer %}
        <style>
            #footer {
                margin-top: 18%;
                margin-bottom: 80px;
                bottom: 0;
                width: 100%;
            }
        </style>
        <div class="row" id="footer">
            <div class="small-7 large-centered columns">
		    <span><big><b>本项目基于: </b></big><span>
                <a href="http://threatstream.com"><img width="158" height="25" src="/static/img/tslogo.png" /></a>
                    <span><big><b>平台的MHN项目</b></big><span>
            </div>
        </div>
        {% endblock %}
        <script src="/static/js/vendor/fastclick.js"></script>
        <script>
            $(document).foundation();
        </script>
    </body>
</html>

server/mhn/templates/pagination.html
{% macro render_pagination(items, view, args) %}
{% if items.pages > 1 %}
<div class="pagination-centered">
    <ul class="pagination">
        {% if items.page > 1 %}
        {% set _ = args.update({'page': items.page - 1}) %}
        <li class="arrow"><a href="{{ url_for(view, **args) }}">&laquo;</a></li>
        {% endif %}
        {% for page in items.iter_pages() %}
        {% if not page %}
        <li class="unavailable" style="color:#999;">&hellip;</li>
        {% else %}
        {% set _ = args.update({'page': page}) %}
        <li class={% if page == items.page %}"current"{% endif %}>
            <a href="{{ url_for(view, **args) }}">{{ page }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if items.pages > items.page %}
        {% set _ = args.update({'page': items.page + 1}) %}
        <li class="arrow"><a href="{{ url_for(view, **args) }}">&raquo;</a></li>
        {% endif %}
    </ul>
</div>
{% endif %}
{% endmacro %}